markdown: rdiscount
permalink: :title.html
url: http://www.noyobo.com
#url: http://localhost:4000
lsi: false
gsl: true
pygments: true
safe: true
auto: true

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
exclude:     []
keep_files:  ['.git','.svn']
timezone:    nil
encoding:    nil

paginate: 5

# presonal config
title: noyobo's Blog (大宝)
feed: http://www.noyobo.com/feed.xml
comments: duoshuo

author:
  name: noyobo
  nickname: noyobo
  email: noyobo@gmail.com
  site: http://www.noyobo.com

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir: 
